[theme]
primaryColor = "#117100ff"               # Um tom escuro e forte de verde
backgroundColor = "#ffffff"           #  branco
secondaryBackgroundColor = "#e6e6e6"  # Painel  claro
textColor = "#000000"                 # Texto ora preto
font = "sans serif"